<map version="freeplane 1.11.1">
<!--To view this file, download free mind mapping software Freeplane from https://www.freeplane.org -->
<node TEXT="Защита информации.&#xa;ОСНОВНЫЕ ТЕРМИНЫ И ОПРЕДЕЛЕНИЯ" LOCALIZED_STYLE_REF="AutomaticLayout.level.root" FOLDED="false" ID="ID_1090958577" CREATED="1409300609620" MODIFIED="1684939419432" ICON_SIZE="12 pt" COLOR="#ffffff" BACKGROUND_COLOR="#002b36" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="20 px" SHAPE_VERTICAL_MARGIN="20 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="3.1 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" VGAP_QUANTITY="3 pt" SHAPE_HORIZONTAL_MARGIN_QUANTITY="10 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="10 pt">
<font NAME="SansSerif" SIZE="18" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<hook NAME="accessories/plugins/AutomaticLayout.properties" VALUE="ALL"/>
<hook NAME="MapStyle" background="#fdf6e3" zoom="0.378">
    <properties show_icon_for_attributes="true" edgeColorConfiguration="#808080ff,#ff0000ff,#0000ffff,#00ff00ff,#ff00ffff,#00ffffff,#7c0000ff,#00007cff,#007c00ff,#7c007cff,#007c7cff,#7c7c00ff" show_note_icons="true" associatedTemplateLocation="template:/light_solarized_template.mm" fit_to_viewport="false"/>

<map_styles>
<stylenode LOCALIZED_TEXT="styles.root_node" STYLE="oval" UNIFORM_SHAPE="true" VGAP_QUANTITY="24 pt">
<font SIZE="24"/>
<stylenode LOCALIZED_TEXT="styles.predefined" POSITION="bottom_or_right" STYLE="bubble">
<stylenode LOCALIZED_TEXT="default" ID="ID_271890427" ICON_SIZE="12 pt" COLOR="#000000" STYLE="fork">
<arrowlink SHAPE="CUBIC_CURVE" COLOR="#000000" WIDTH="2" TRANSPARENCY="200" DASH="" FONT_SIZE="9" FONT_FAMILY="SansSerif" DESTINATION="ID_271890427" STARTARROW="NONE" ENDARROW="DEFAULT"/>
<font NAME="SansSerif" SIZE="10" BOLD="false" ITALIC="false"/>
<richcontent CONTENT-TYPE="plain/auto" TYPE="DETAILS"/>
<richcontent TYPE="NOTE" CONTENT-TYPE="plain/auto"/>
</stylenode>
<stylenode LOCALIZED_TEXT="defaultstyle.details"/>
<stylenode LOCALIZED_TEXT="defaultstyle.attributes">
<font SIZE="9"/>
</stylenode>
<stylenode LOCALIZED_TEXT="defaultstyle.note" COLOR="#000000" BACKGROUND_COLOR="#ffffff" TEXT_ALIGN="LEFT"/>
<stylenode LOCALIZED_TEXT="defaultstyle.floating">
<edge STYLE="hide_edge"/>
<cloud COLOR="#f0f0f0" SHAPE="ROUND_RECT"/>
</stylenode>
<stylenode LOCALIZED_TEXT="defaultstyle.selection" BACKGROUND_COLOR="#afd3f7" BORDER_COLOR_LIKE_EDGE="false" BORDER_COLOR="#afd3f7"/>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.user-defined" POSITION="bottom_or_right" STYLE="bubble">
<stylenode LOCALIZED_TEXT="styles.topic" COLOR="#18898b" STYLE="fork">
<font NAME="Liberation Sans" SIZE="10" BOLD="true"/>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.subtopic" COLOR="#cc3300" STYLE="fork">
<font NAME="Liberation Sans" SIZE="10" BOLD="true"/>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.subsubtopic" COLOR="#669900">
<font NAME="Liberation Sans" SIZE="10" BOLD="true"/>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.important" ID="ID_67550811">
<icon BUILTIN="yes"/>
<arrowlink COLOR="#003399" TRANSPARENCY="255" DESTINATION="ID_67550811"/>
</stylenode>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.AutomaticLayout" POSITION="bottom_or_right" STYLE="bubble">
<stylenode LOCALIZED_TEXT="AutomaticLayout.level.root" COLOR="#000000" STYLE="oval" SHAPE_HORIZONTAL_MARGIN="10 pt" SHAPE_VERTICAL_MARGIN="10 pt">
<font SIZE="18"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,1" COLOR="#0033ff">
<font SIZE="16"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,2" COLOR="#00b439">
<font SIZE="14"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,3" COLOR="#990000">
<font SIZE="12"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,4" COLOR="#111111">
<font SIZE="10"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,5"/>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,6"/>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,7"/>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,8"/>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,9"/>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,10"/>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,11"/>
</stylenode>
</stylenode>
</map_styles>
</hook>
<node TEXT="Область применения" POSITION="bottom_or_right" ID="ID_1447779137" CREATED="1684937145558" MODIFIED="1684939442658" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#073642" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="-399 pt" VSHIFT_QUANTITY="1325 pt" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="16" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Биография" POSITION="bottom_or_right" ID="ID_1050236059" CREATED="1684937223200" MODIFIED="1684939674035" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#073642" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="56 pt" VSHIFT_QUANTITY="-223 pt" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="16" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="Федеральный закон от 27.07.2006 N 149-ФЗ" ID="ID_449725850" CREATED="1684939514794" MODIFIED="1684939573120" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#586e75" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="Об информации, информационных технологиях и о защите информации" ID="ID_1080432305" CREATED="1684939583895" MODIFIED="1684939584637" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Федеральный закон от 29.07.2004 N 98-ФЗ" ID="ID_361999622" CREATED="1684939591923" MODIFIED="1684939598637" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#586e75" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="О коммерческой тайне" ID="ID_1254229571" CREATED="1684939605113" MODIFIED="1684939605687" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Рекомендации по стандартизации Р 50.1.056-2005" ID="ID_1512479219" CREATED="1684939613623" MODIFIED="1684939628737" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#586e75" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node POSITION="bottom_or_right" ID="ID_275400453" CREATED="1684939636907" MODIFIED="1684939636907" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt"><richcontent TYPE="NODE">

<html>
  <head>
    
  </head>
  <body>
    <span style="font-size: 11.0pt; line-height: 107%; font-family: Calibri,sans-serif"><font size="11.0pt" face="Calibri,sans-serif">&#1058;&#1077;&#1093;&#1085;&#1080;&#1095;&#1077;&#1089;&#1082;&#1072;&#1103; &#1079;&#1072;&#1097;&#1080;&#1090;&#1072; &#1080;&#1085;&#1092;&#1086;&#1088;&#1084;&#1072;&#1094;&#1080;&#1080;.</font></span>
  </body>
</html>
</richcontent>
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Основные термины и определения" ID="ID_862045634" CREATED="1684939645058" MODIFIED="1684939645543" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
</node>
<node TEXT="Приложение А (справочное)" POSITION="bottom_or_right" ID="ID_1136464669" CREATED="1684937241613" MODIFIED="1684939657565" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#073642" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="147.5 pt" VSHIFT_QUANTITY="-1133 pt" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="16" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="ТЕРМИНЫ И ОПРЕДЕЛЕНИЯ ОБЩЕТЕХНИЧЕСКИХ ПОНЯТИЙ" ID="ID_500414378" CREATED="1684939012646" MODIFIED="1684939156922" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#586e75" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" VGAP_QUANTITY="3 pt" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="Информация" ID="ID_684321226" CREATED="1684939024037" MODIFIED="1684939025362" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="сведения (сообщения, данные) независимо от формы их представления" ID="ID_1025994762" CREATED="1684939028442" MODIFIED="1684939089527" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#839496" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Документированная информация" ID="ID_929987834" CREATED="1684939106208" MODIFIED="1684939106945" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="зафиксированная на материальном носителе путем документирования информация с реквизитами" ID="ID_916532944" CREATED="1684939111032" MODIFIED="1684939119277" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#839496" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Данные" ID="ID_1478796257" CREATED="1684939133208" MODIFIED="1684939202523" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="факты, понятия или команды, представленные в формализованном виде и позволяющие осуществлять их передачу или обработку как вручную, так и с помощью средств автоматизации." ID="ID_1102088071" CREATED="1684939204304" MODIFIED="1684939208093" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#839496" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Носитель информации" ID="ID_774896510" CREATED="1684939134227" MODIFIED="1684939212359" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="материальный объект, в том числе физическое поле, в котором информация находит свое отображение в виде символов, образов, сигналов, технических решений и процессов, количественных характеристик физических величин." ID="ID_65582253" CREATED="1684939216471" MODIFIED="1684939217294" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#839496" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Информационная система" ID="ID_1077895633" CREATED="1684939134606" MODIFIED="1684939223499" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="совокупность содержащейся в базах данных информации и обеспечивающих ее обработку информационных технологий и технических средств" ID="ID_1370180771" CREATED="1684939227047" MODIFIED="1684939227694" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#839496" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Обладатель информации" ID="ID_1808542944" CREATED="1684939134951" MODIFIED="1684939232626" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="лицо, самостоятельно создавшее информацию либо получившее на основании закона или договора право разрешать или ограничивать доступ к информации, определяемой по каким-либо признакам" ID="ID_30791916" CREATED="1684939237068" MODIFIED="1684939238409" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#839496" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Пользователь информации" ID="ID_466876513" CREATED="1684939135337" MODIFIED="1684939242909" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="субъект, пользующийся информацией, полученной от ее собственника, владельца или посредника, в соответствии с установленными правами и правилами доступа к информации либо с их нарушением." ID="ID_1754091943" CREATED="1684939246889" MODIFIED="1684939247891" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#839496" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Доступ к информации" ID="ID_1634298146" CREATED="1684939135728" MODIFIED="1684939252285" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="возможность получения информации и ее использования" ID="ID_1641175375" CREATED="1684939256519" MODIFIED="1684939257259" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#839496" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Право доступа к защищаемой информации; право доступа" ID="ID_682686660" CREATED="1684939136084" MODIFIED="1684939274741" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" VGAP_QUANTITY="3 pt" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="совокупность правил доступа к защищаемой информации, установленных правовыми документами или собственником, владельцем информации." ID="ID_1406851859" CREATED="1684939269588" MODIFIED="1684939274739" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#839496" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Правило доступа к защищаемой информации; правило доступа" ID="ID_725168112" CREATED="1684939136491" MODIFIED="1684939276792" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="совокупность правил, устанавливающих порядок и условия доступа субъекта к защищаемой информации и ее носителям." ID="ID_629205810" CREATED="1684939278231" MODIFIED="1684939286783" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#839496" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Конфиденциальность информации" ID="ID_562362271" CREATED="1684939136878" MODIFIED="1684939292053" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="обязательное для выполнения лицом, получившим доступ к определенной информации, требование не передавать такую информацию третьим лицам без согласия ее обладателя" ID="ID_1237886200" CREATED="1684939295559" MODIFIED="1684939296081" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#839496" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Распространение информации" ID="ID_1385060777" CREATED="1684939137283" MODIFIED="1684939323692" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="действия, направленные на получение информации неопределенным кругом лиц или передачу информации неопределенному кругу лиц" ID="ID_1154863081" CREATED="1684939328477" MODIFIED="1684939329364" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#839496" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Оператор информационной системы" ID="ID_738142645" CREATED="1684939137682" MODIFIED="1684939335111" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="гражданин или юридическое лицо, осуществляющее деятельность по эксплуатации информационной системы, в том числе по обработке информации, содержащейся в ее базах данных" ID="ID_542365336" CREATED="1684939339365" MODIFIED="1684939339942" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#839496" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Доступность информации [ресурсов информационной системы]" ID="ID_1896155930" CREATED="1684939138047" MODIFIED="1684939354957" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="состояние информации [ресурсов информационной системы], при котором субъекты, имеющие права доступа, могут реализовать их беспрепятственно" ID="ID_1106545017" CREATED="1684939360049" MODIFIED="1684939360607" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#839496" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Целостность" ID="ID_500372591" CREATED="1684939138400" MODIFIED="1684939365924" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="состояние информации, при котором отсутствует любое ее изменение либо изменение осуществляется только преднамеренно субъектами, имеющими на него право." ID="ID_1555612166" CREATED="1684939369948" MODIFIED="1684939370691" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#839496" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node POSITION="bottom_or_right" ID="ID_67874033" CREATED="1684939141525" MODIFIED="1684939141525" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt"><richcontent TYPE="NODE">

<html>
  <head>
    
  </head>
  <body>
    <span style="font-size: 11.0pt; line-height: 107%; font-family: Calibri,sans-serif"><font size="11.0pt" face="Calibri,sans-serif">&#1048;&#1085;&#1092;&#1086;&#1088;&#1084;&#1072;&#1094;&#1080;&#1103;, &#1089;&#1086;&#1089;&#1090;&#1072;&#1074;&#1083;&#1103;&#1102;&#1097;&#1072;&#1103; &#1082;&#1086;&#1084;&#1084;&#1077;&#1088;&#1095;&#1077;&#1089;&#1082;&#1091;&#1102; &#1090;&#1072;&#1081;&#1085;&#1091;</font></span>
  </body>
</html>
</richcontent>
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="научно-техническая, технологическая, производственная, финансово-экономическая или иная информация (в том числе составляющая секреты производства (ноу-хау)), которая имеет действительную или потенциальную коммерческую ценность в силу неизвестности ее третьим лицам, к которой нет свободного доступа на законном основании и в отношении которой обладателем такой информации введен режим коммерческой тайны" ID="ID_1419753037" CREATED="1684939144352" MODIFIED="1684939151961" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#839496" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node POSITION="bottom_or_right" ID="ID_616509951" CREATED="1684939300956" MODIFIED="1684939300956" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt"><richcontent TYPE="NODE">

<html>
  <head>
    
  </head>
  <body>
    <span style="font-size: 11.0pt; line-height: 107%; font-family: Calibri,sans-serif"><font size="11.0pt" face="Calibri,sans-serif">&#1055;&#1088;&#1077;&#1076;&#1086;&#1089;&#1090;&#1072;&#1074;&#1083;&#1077;&#1085;&#1080;&#1077; &#1080;&#1085;&#1092;&#1086;&#1088;&#1084;&#1072;&#1094;&#1080;&#1080;</font></span>
  </body>
</html>
</richcontent>
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="действия, направленные на получение информации определенным кругом лиц или передачу информации определенному кругу лиц" ID="ID_1050525796" CREATED="1684939308791" MODIFIED="1684939310541" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#839496" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
</node>
</node>
<node TEXT="Термины и определения" POSITION="top_or_left" ID="ID_1227674445" CREATED="1684937230752" MODIFIED="1684937240588" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#073642" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="16" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="Термины, относящиеся к видам защиты информации" POSITION="top_or_left" ID="ID_189633715" CREATED="1684937567809" MODIFIED="1684937586787" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#586e75" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="правовая защита информации" ID="ID_601119774" CREATED="1684937606489" MODIFIED="1684937608504" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="техническая защита информации" ID="ID_1746934392" CREATED="1684937614540" MODIFIED="1684937616744" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="криптографическая защита информации" ID="ID_1112691172" CREATED="1684937622694" MODIFIED="1684937624365" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="физическая защита информации" ID="ID_427504637" CREATED="1684937629148" MODIFIED="1684937630998" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Общие понятия" ID="ID_751039288" CREATED="1684937715033" MODIFIED="1684937723047" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#586e75" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="Защита информации" POSITION="top_or_left" ID="ID_1541467758" CREATED="1684937433054" MODIFIED="1684937444061" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Термины, относящиеся к способам защиты информации" ID="ID_1604169854" CREATED="1684937757031" MODIFIED="1684937770740" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#586e75" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="способ защиты информации" ID="ID_396910883" CREATED="1684937775342" MODIFIED="1684937776508" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="защита информации от утечки" ID="ID_164702236" CREATED="1684937780558" MODIFIED="1684937781694" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="защита информации от несанкционированного воздействия" ID="ID_268604127" CREATED="1684937783242" MODIFIED="1684937788847" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="защита информации от непреднамеренного воздействия" ID="ID_1807877223" CREATED="1684937794932" MODIFIED="1684937796077" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="защита информации от разглашения" ID="ID_479511209" CREATED="1684937801005" MODIFIED="1684937802072" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="защита информации от несанкционированного доступа" ID="ID_1794821791" CREATED="1684937807761" MODIFIED="1684937810200" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="защита информации от преднамеренного воздействия" ID="ID_180314799" CREATED="1684937815693" MODIFIED="1684937816604" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="защита информации от [иностранной] разведки" ID="ID_955550246" CREATED="1684937822053" MODIFIED="1684937823692" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Термины, относящиеся к замыслу защиты информации" ID="ID_1131470896" CREATED="1684937849185" MODIFIED="1684937853644" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#586e75" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="замысел защиты информации" ID="ID_1645353757" CREATED="1684937862117" MODIFIED="1684937863236" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="цель защиты информации" ID="ID_894848031" CREATED="1684937866828" MODIFIED="1684937868218" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="система защиты информации" ID="ID_185969910" CREATED="1684937872713" MODIFIED="1684937873580" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="политика безопасности (информации в организации)" ID="ID_1243212986" CREATED="1684937878390" MODIFIED="1684937879254" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="безопасность информации [данных]" ID="ID_1641455945" CREATED="1684938487618" MODIFIED="1684938617198" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Термины, относящиеся к объекту защиты информации" ID="ID_1332552412" CREATED="1684938672349" MODIFIED="1684938675151" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#586e75" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="объект защиты информации" ID="ID_1388488321" CREATED="1684938681530" MODIFIED="1684938682767" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="защищаемая информация" ID="ID_1784873497" CREATED="1684938689450" MODIFIED="1684938690300" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="носитель защищаемой информации" ID="ID_693929616" CREATED="1684938695129" MODIFIED="1684938695833" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="защищаемый объект информатизации" ID="ID_1990542354" CREATED="1684938701238" MODIFIED="1684938701958" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="защищаемая информационная система" ID="ID_1567587843" CREATED="1684938707132" MODIFIED="1684938707784" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Термины, относящиеся к угрозам безопасности информации" ID="ID_541312241" CREATED="1684938720628" MODIFIED="1684938721815" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#586e75" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="угроза (безопасности информации)" ID="ID_59297115" CREATED="1684938744022" MODIFIED="1684938744819" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="фактор, воздействующий на защищаемую информацию" ID="ID_778653025" CREATED="1684938750135" MODIFIED="1684938751178" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="источник угрозы безопасности информации" ID="ID_1324085818" CREATED="1684938758464" MODIFIED="1684938759316" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="уязвимость (информационной системы)" ID="ID_677933072" CREATED="1684938766134" MODIFIED="1684938766879" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="вредоносная программа" ID="ID_331577487" CREATED="1684938774300" MODIFIED="1684938774899" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="несанкционированное воздействие на информацию" ID="ID_1091535636" CREATED="1684938779326" MODIFIED="1684938779891" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="преднамеренное силовое электромагнитное воздействие на информацию" ID="ID_1019252863" CREATED="1684938784305" MODIFIED="1684938784949" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="модель угроз (безопасности информации)" ID="ID_1101904010" CREATED="1684938789300" MODIFIED="1684938790049" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Термины, относящиеся к технике защиты информации" ID="ID_1032368804" CREATED="1684938796770" MODIFIED="1684938797563" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#586e75" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="техника защиты информации" ID="ID_988193412" CREATED="1684938801956" MODIFIED="1684938802646" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="средство защиты информации" ID="ID_979781704" CREATED="1684938805794" MODIFIED="1684938811215" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="средство контроля эффективности защиты информации" ID="ID_869300190" CREATED="1684938812558" MODIFIED="1684938813266" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="средство физической защиты информации" ID="ID_1380853378" CREATED="1684938816960" MODIFIED="1684938818385" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="криптографическое средство защиты информации" ID="ID_1261740607" CREATED="1684938823833" MODIFIED="1684938824532" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Термины, относящиеся к способам оценки соответствия&#xa;требованиям по защите информации" ID="ID_421263634" CREATED="1684938831014" MODIFIED="1684938832372" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#586e75" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="оценка соответствия требованиям по защите информации" ID="ID_590094643" CREATED="1684938837340" MODIFIED="1684938838182" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="лицензирование в области защиты информации" ID="ID_879035695" CREATED="1684938842016" MODIFIED="1684938842616" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="сертификация на соответствие требованиям по безопасности информации" ID="ID_1269369556" CREATED="1684938847024" MODIFIED="1684938847640" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="специальное исследование (объекта защиты информации)" ID="ID_1435745370" CREATED="1684938858290" MODIFIED="1684938859047" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="специальная проверка" ID="ID_1775833140" CREATED="1684938862850" MODIFIED="1684938863598" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="аудиторская проверка информационной безопасности в организации" ID="ID_1085371554" CREATED="1684938867526" MODIFIED="1684938868233" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="мониторинг безопасности информации" ID="ID_1453314622" CREATED="1684938874670" MODIFIED="1684938875412" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="экспертиза документа по защите информации" ID="ID_1430490564" CREATED="1684938879962" MODIFIED="1684938880697" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="анализ информационного риска" ID="ID_269539767" CREATED="1684938890480" MODIFIED="1684938891345" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="оценка информационного риска" ID="ID_221660139" CREATED="1684938897784" MODIFIED="1684938898597" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Термины, относящиеся к эффективности защиты информации" ID="ID_452793183" CREATED="1684938904586" MODIFIED="1684938906918" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#586e75" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<node TEXT="эффективность защиты информации" ID="ID_1381168352" CREATED="1684938911828" MODIFIED="1684938912497" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="требование по защите информации" ID="ID_142745447" CREATED="1684938918567" MODIFIED="1684938919332" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="показатель эффективности защиты информации" ID="ID_833251328" CREATED="1684938923156" MODIFIED="1684938924041" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="норма эффективности защиты информации" ID="ID_1785774288" CREATED="1684938927954" MODIFIED="1684938928573" ICON_SIZE="12 pt" COLOR="#fdf6e3" BACKGROUND_COLOR="#657b83" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
</node>
</node>
</node>
</node>
</map>
